# Generated by Django 2.2.5 on 2023-03-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='statue',
            field=models.IntegerField(default=0),
        ),
    ]
