# Generated by Django 2.2.5 on 2023-03-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_statue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='statue',
            new_name='status',
        ),
    ]
